CREATE TABLE `CHANNEL` (
  `CHANNEL_ID` varchar(20) NOT NULL,
  `CHANNEL_NO` bigint(20) NOT NULL,
  `DISPLAY_NAME` longtext,
  `VERSION` int(11) DEFAULT NULL,
  PRIMARY KEY (`CHANNEL_ID`),
  UNIQUE KEY `UNQ_CHANNEL_0` (`CHANNEL_ID`,`CHANNEL_NO`),
  KEY `CHANNEL_NO_I` (`CHANNEL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PROGRAMME` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EVENT_ID` bigint(20) NOT NULL,
  `START_DATETIME` datetime NOT NULL,
  `STOP_DATETIME` datetime NOT NULL,
  `TITLE` longtext NOT NULL,
  `CHANNEL_ID` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNQ_PROGRAMME_0` (`CHANNEL_ID`,`EVENT_ID`),
  KEY `CHANNEL_ID_I` (`CHANNEL_ID`),
  KEY `EVENT_ID_I` (`EVENT_ID`),
  KEY `START_DATETIME_I` (`START_DATETIME`),
  KEY `STOP_DATETIME_I` (`STOP_DATETIME`),
  CONSTRAINT `FK_PROGRAMME_CHANNEL_ID` FOREIGN KEY (`CHANNEL_ID`) REFERENCES `CHANNEL` (`CHANNEL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8;

/*
除外チャンネル情報テーブル。番組情報の更新時にこのテーブル除外チャンネル情報テーブルの内容を転記する。
*/
CREATE TABLE `EXCLUDECHANNEL` (
  `CHANNEL_ID` varchar(20) NOT NULL,
  PRIMARY KEY (`CHANNEL_ID`),
  UNIQUE KEY `CHANNEL_ID` (`CHANNEL_ID`),
  CONSTRAINT `FK_EXCLUDE_CHANNEL_ID` FOREIGN KEY (`CHANNEL_ID`) REFERENCES `CHANNEL` (`CHANNEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*
除外チャンネル情報の転記元テーブル。番組情報の更新時にこのテーブルから除外チャンネルを除外チャンネル情報テーブルへ転記する。
*/
CREATE TABLE `TEMP_EXCLUDECHANNEL` (
  `CHANNEL_ID` varchar(20) NOT NULL,
  PRIMARY KEY (`CHANNEL_ID`),
  UNIQUE KEY `CHANNEL_ID` (`CHANNEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;